### ISSUE TITLE
Реализовать роут с api  CRUD-методов модели Суперадмина микросервиса базы данных

### ISSUE THREAD

**Issue by phgithubacc** [latecore-test/rco-vps-complex#19]
Выбрать роут и четыре базовых эндпоинта под CRUD модели Суперадмина.
Использовать http-метод POST обработки запросов на все эндпоинты роута

**Comment by KOVALcraft** [comment]
выполнено,
создал директорию routes в ней файл adm.routes для superadmin с 4мя эндпоинтами под CRUD по http-методу POST обработки запросов

**Comment by phgithubacc** [comment]
Файл adm.routes
/create
Суперадмин должен иметь возможность создаваться без информации о дистрибьютере.

/update
В if для проверки на пароль в начале пропущен восклицательный знак логического отрицания. В итоге сообщение о предложение попробовать другой пароль возникнет как раз если superadminPass окажется найденным.

**Comment by KOVALcraft** [comment]
Файл adm.routes
/create
Суперадмин должен иметь возможность создаваться без информации о дистрибьютере.

/update
В if для проверки на пароль в начале пропущен восклицательный знак логического отрицания. В итоге сообщение о предложение попробовать другой пароль возникнет как раз если superadminPass окажется найденным.

пофиксил
