### ISSUE TITLE
Реализовать роут с api CRUD-методов модели Дистрибьютера микросервиса базы данных

### ISSUE THREAD

**Issue by phgithubacc** [latecore-test/rco-vps-complex#20]
Выбрать роут и четыре базовых эндпоинта под CRUD модели Дистрибьютера.
Использовать http-метод POST обработки запросов на все эндпоинты роута

**Comment by KOVALcraft** [comment]
выполнено,
создал директорию routes в ней файл dis.routes для distributor с 4мя эндпоинтами под CRUD по http-методу POST обработки запросов

**Comment by phgithubacc** [comment]
/update
Должна присутствовать возможность изменять не только значение цены электричества, а любое доступное пользователю поле своего профайла.

**Comment by KOVALcraft** [comment]
/update
Должна присутствовать возможность изменять не только значение цены электричества, а любое доступное пользователю поле своего профайла.

учтено
