### ISSUE TITLE
Реализовать роут с api CRUD-методов модели Менеджера микросервиса базы данных

### ISSUE THREAD

**Issue by phgithubacc** [latecore-test/rco-vps-complex#21]
Выбрать роут и четыре базовых эндпоинта под CRUD модели Менеджера.
Использовать http-метод POST обработки запросов на все эндпоинты роута

**Comment by KOVALcraft** [comment]
выполнено,
создал директорию routes в ней файл mng.routes для manager с 4мя эндпоинтами под CRUD по http-методу POST обработки запросов

**Comment by phgithubacc** [comment]
/update
Должна присутстовать возможность изменять любое доступное пользователю поле своего профайла, а не только full_name

**Comment by KOVALcraft** [comment]
/update
Должна присутстовать возможность изменять любое доступное пользователю поле своего профайла, а не только full_name

учтено
