### ISSUE TITLE
Реализовать на микросервисе следующие отношения меджу моделями

### ISSUE THREAD

**Issue by phgithubacc** [latecore-test/rco-vps-complex#23]
Суперадмин-дистрибьютер : один-ко-многим
Дистрибьютер-менеджер : один-ко-многим

**Comment by KOVALcraft** [comment]
Реализовано

**Comment by phgithubacc** [comment]
Необходимо поправить ишью с лейблой to fix
Так все выглядит правильным и соответствующим техническому заданию.
